version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/osobe_db
      - SPRING_DATASOURCE_USERNAME=korisnik
      - SPRING_DATASOURCE_PASSWORD=lozinka
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend-osobe
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: osobe_db
      POSTGRES_USER: korisnik
      POSTGRES_PASSWORD: lozinka
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: